'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
// import i18n  from '../../i18n'
import i18n  from '@/../../i18n'
import ReduxProvider from "./store/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let [defaultLang,setDefaultLang] = useState('en')
  useEffect(()=>{
    if(!localStorage.getItem('lang')){
      localStorage.setItem('lang','en')
    }
    setDefaultLang(localStorage.getItem('lang') || 'en')
},[])
  useEffect(()=>{
    i18n.changeLanguage(defaultLang)
  },[defaultLang])
  return (
    <html lang="en">
      <body dir={defaultLang == 'en' ? 'ltr' : 'rtl' }
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
